### Numpy
1. Python library used to perform complex mathematical operations and scientific computing.
2. Operated primarily on multidimensional arrays.
3. Stands for numerical python and is an open source library.

In [2]:
#Installing Numpy in jupyter notebook
!pip install Numpy

In [4]:
#Importing numpy
import numpy as np

In [5]:
list=[1,2,3,4]

In [6]:
type(list)

list

In [8]:
#Converting list to array using numpy
arr=np.array(list)
arr

array([1, 2, 3, 4])

In [9]:
#Checking type of array
type(arr)

numpy.ndarray

In [11]:
#checking size of array
arr.size

4

In [13]:
#Creating array of n zeroes.
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
#Creating array of n ones.
x=np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
#one dimensional array
o=np.array([1,2,3,4])
o

array([1, 2, 3, 4])

In [16]:
#Checking dimension
o.ndim

1

In [17]:
#Checking no of rows and cols (r,c)
o.shape

(4,)

In [21]:
#two dimensional array
t=np.array([[1,2,3],[4,5,6],[7,8,9],[4,9,6]])
t

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 9, 6]])

In [22]:
t.ndim

2

In [23]:
t.shape

(4, 3)

In [24]:
#Reshaping it to 3d array
t=t.reshape(3,2,2)
t

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 4],
        [9, 6]]])

In [26]:
t.ndim

3

In [27]:
t.shape

(3, 2, 2)

In [29]:
t=t.reshape(3,4)
t

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 4, 9, 6]])

### Indexing

#### Accessing 1D array elements 

In [31]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [33]:
#Grabbing specific element from array - 1D case
arr[1]

2

In [34]:
#Array elements in operations
arr[1]+arr[2]

5

#### Acessing 2D array elements 

In [49]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [38]:
#Acessing specific element from array - 2D case
print("2nd element in 1st dimension:",arr[0,1])


2nd element in 1st dimension: 2


In [39]:
print("2nd elmement in 2nd dimenstion:", arr[1,1])

2nd elmement in 2nd dimenstion: 7


In [40]:
print("5th element in 2nd dimenstion:",arr[1,4])

5th element in 2nd dimenstion: 10


In [41]:
#linspace function - creates evently spaced values over an interval
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [42]:
#Creating an identity of matrix of specified dimension
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
#Generate random number array
np.random.randint(0,10,10)

array([4, 4, 7, 7, 7, 0, 3, 3, 3, 8])

In [46]:
#Generate random floating point numbers - 3 by 3 matrix
np.random.rand(3,3)

array([[0.72867095, 0.10632025, 0.88054921],
       [0.86842498, 0.73954715, 0.9208285 ],
       [0.02416178, 0.16058358, 0.2013874 ]])

In [50]:
#Checking maximum value in array
arr.max()

10

In [51]:
#Checking index where maximum element is present
arr.argmax()

9

In [52]:
#Creating evenly spaced values within an interval
np.arange(0,11,3)

array([0, 3, 6, 9])

### Slicing

In [55]:
a=np.arange(0,11,2)
a

array([ 0,  2,  4,  6,  8, 10])

In [57]:
#Accessing 2,4 from above array
a[1:3]

array([2, 4])

In [58]:
#2d array
a=np.array([[1,2,3],[2,3,4],[4,5,6]])
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [59]:
#Acessing 1,2
a[0:1,0:2]

array([[1, 2]])

In [68]:
#Acessing 2,3,3,4
a[0:2,1:3]

array([[2, 3],
       [3, 4]])

In [70]:
a=np.arange(0,11,2)
a

array([ 0,  2,  4,  6,  8, 10])

In [72]:
a1=np.arange(0,11,2)
a1

array([ 0,  2,  4,  6,  8, 10])

In [73]:
#Adding two arrays
c=a+a1
c

array([ 0,  4,  8, 12, 16, 20])

In [74]:
#Square root
np.sqrt(c)

array([0.        , 2.        , 2.82842712, 3.46410162, 4.        ,
       4.47213595])

In [75]:
#Sin function
np.sin(c)

array([ 0.        , -0.7568025 ,  0.98935825, -0.53657292, -0.28790332,
        0.91294525])

In [76]:
#Copying array from one to another
arr=np.array([1,2,3,4,5])
x=arr.copy()
x

array([1, 2, 3, 4, 5])

In [77]:
#Create an array 5*5 which should contain from 0 to 24
arr=np.arange(25)
arr.reshape(5,5)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])